export default [
  [
    [20, "While attuned to the artifact, you gain proficiency in one skill of the DM's choice"],
    [30, "While attuned to the artifact, you are immune to disease."],
    [40, "While attuned to the artifact, you can't be charmed or frightened."],
    [50, "While attuned to the artifact, you have resistance against one damage type of the DM's choice."],
    [60, "While attuned to the artifact, you can use an action to cast one cantrip (chosen by the DM) from it."],
    [70, "While attuned to the artifact, you can use an action to cast one 1st level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [80, "While attuned to the artifact, you can use an action to cast one 2nd level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [90, "While attuned to the artifact, you can use an action to cast one 3rd level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [100, "While attuned to the artifact, you gain +1 AC."],
  ],
  [
    [20, "While attuned to the artifact, one of your ability score (chosen by the DM) increases by 2 to a maximum of 24"],
    [30, "While attuned to the artifact, you regain 1d6 hit points at the start of your turn if you have at least 1 hit point."],
    [40, "While attuned to the artifact, when you hit with a weapon attack, the target takes 1d6 extra damage of the weapon's type."],
    [50, "While attuned to the artifact, your walking speed increases by 10ft."],
    [60, "While attuned to the artifact, you can use an action to cast one 4th level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [70, "While attuned to the artifact, you can use an action to cast one 5th level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [80, "While attuned to the artifact, you can use an action to cast one 6th level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [90, "While attuned to the artifact, you can use an action to cast one 7th level spell (chosen by the DM) from it. After casting the spell, roll a d6. On a roll of 1-5, you can't cast it again until the next dawn."],
    [100, "While attuned to the artifact, you can't be blinded, deafened, petrified or stunned."],
  ],
  [
    [5, "While attuned to the artifact, you have disadvantage on saving throws against spells."],
    [10, "The first time you touch a gem or piece of jewelry while attuned to this artifact, the value of the gem or jewelry is reduced by half."],
    [15, "While attuned to the artifact, you are blinded when you are more than 10 feet away from it."],
    [20, "While attuned to the artifact, you have disadvantage on saving throws against poison."],
    [30, "While attuned to the artifact, you emit a sour stench noticeable from up to 10 feet away."],
    [35, "While attuned to the artifact, all holy water within 10 feet of you is destroyed."],
    [40, "While attuned to the artifact, you are physically ill and have disadvantage on any ability check or saving throw that uses Strength or Constitution."],
    [45, "While attuned to the artifact, your weight increases by 1d4 x 10 pounds."],
    [50, "While attuned to the artifact, your appearance changes as the OM decides."],
    [55, "While attuned to the artifact, you are deafened when you are more than 10 feet away from it."],
    [60, "While attuned to the artifact, your weight drops by 1d4 x 5 pounds."],
    [65, "While attuned to the artifact, you can't smell."],
    [70, "While attuned to the artifact, nonmagical flames are extinguished within 30 feet of you."],
    [80, "While you are attuned to the artifact, other creatures can't take short or long rests while within 300 feet of you."],
    [85, "While attuned to the artifact, you deal 1d6 necrotic damage to any plant you touch that isn't a creature."],
    [90, "While you are attuned to the artifact, animals within 30 feet of you are hostile toward you."],
    [95, "While attuned to the artifact, you must eat and drink six times the normal amount each day."],
    [100, "While you are attuned to the artifact, your flaw is amplified in a way determined by the OM."],
  ],
  [
    [5, "While you are attuned to the artifact, your body rots over the course of four days, after which the rotting stops. You lose your hair by the end of day 1, finger tips and toe tips by the end of day 2, lips and nose by the end of day 3, and ears by the end ofday 4. A regenerate spell restores lost body parts."],
    [10, "While you are attuned to the artifact, you determine your alignment daily at dawn by rolling a d6 twice. On the first roll, a 1- 2 indicates lawful, 3-4 neutral, and S-6 chaotic. On the second roll, a 1-2 indicates good, 3-4 neutral, and 5-6 evil."],
    [15, "When you first attune to the artifact, it gives you a quest determined by the OM. You must complete this quest as if affected by the geas spell. Once you complete the quest, you are no longer affected by this property."],
    [20, "The artifact houses a bodiless life force that is hostile toward you. Each time you use an action to use one ofthe artifact's properties, there is a 50 percent chance that the life force tries to leave the artifact and enter your body. If you fail a DC 20 Charisma saving throw, it succeeds , and you become an NPC under the OM's control until the intruding life force is banished using magic such as the dispel evil and good spell."],
    [25, "Creatures with a challenge rating of O, as well as plants that aren't creatures, drop to 0 hit points when within 10 feet of the artifact."],
    [30, "The artifact imprisons a death slaad (see the Monster Manual). Each time you use one ofthe artifact's properties as an action, the slaad has a 10 percent chance of escaping, whereupon it appears within 15 feet ofyou and attacks you."],
    [35, "While you are attuned to the artifact, creatures of a particular type other than humanoid (as chosen by the OM) are always hostile toward you."],
    [40, "The artifact dilutes magic potions within 10 feet of it, rendering them nonmagical."],
    [45, "The artifact erases magic scrolls within 10 feet of it, rendering them nonmagical."],
    [50, "Before using one of the artifact's properties as an action, you must use a bonus action to draw blood, either from yourself or from a willing or incapacitated creature within your reach, using a piercing or slashing melee weapon. The subject takes 1d4 damage of the appropriate type."],
    [60, "When you become attuned to the artifact, you gain a form of long-term madness (see chapter 8, \"Running the Game\")."],
    [65, "You take 4d10 psychic damage when you become attuned to the artifact."],
    [70, "You take 8d10 psychic damage when you become attuned to the artifact."],
    [75, "Before you can become attuned to the artifact, you must kill a creature of your alignment."],
    [80, "When you become attuned to the artifact, one of your ability scores is reduced by 2 at random. A greater restoration spell restores the ability to normal."],
    [85, "Each time you become attuned to the artifact, you age 3d10 years. You must succeed on a DC 10 Constitution saving throw or die from the shock. If you die, you are instantly transformed into a wight (see the Monster Manual) under the OM's control that is sworn to protect the artifact."],
    [90, "While attuned to the artifact, you lose the ability to speak."],
    [95, "While attuned to the artifact, you have vulnerability to all damage."],
    [100, "When you become attuned to the artifact, there is a 10 percent chance that you attract the attention of a god that sends an avatar to wrest the artifact from you. The avatar has the same alignment as its creator and the statistics of an empyrean (see the Monster Manual). Once it obtains the artifact, the avatar vanishes."]
  ],
];
